/* 
 * Higgs API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FileApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class FileApiTests
    {
        private FileApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new FileApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FileApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' FileApi
            //Assert.IsInstanceOfType(typeof(FileApi), instance, "instance is a FileApi");
        }

        
        /// <summary>
        /// Test FileByIdGet
        /// </summary>
        [Test]
        public void FileByIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //instance.FileByIdGet(id);
            
        }
        
        /// <summary>
        /// Test FileGet
        /// </summary>
        [Test]
        public void FileGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //instance.FileGet(id);
            
        }
        
        /// <summary>
        /// Test FilePost
        /// </summary>
        [Test]
        public void FilePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AddFileRequest request = null;
            //instance.FilePost(request);
            
        }
        
    }

}
