/* 
 * Higgs API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// AddUserScopeRequest
    /// </summary>
    [DataContract]
    public partial class AddUserScopeRequest :  IEquatable<AddUserScopeRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddUserScopeRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AddUserScopeRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AddUserScopeRequest" /> class.
        /// </summary>
        /// <param name="UserId">User to add the scope to (required).</param>
        /// <param name="Scope">Scope to add (required).</param>
        public AddUserScopeRequest(int? UserId = default(int?), string Scope = default(string))
        {
            // to ensure "UserId" is required (not null)
            if (UserId == null)
            {
                throw new InvalidDataException("UserId is a required property for AddUserScopeRequest and cannot be null");
            }
            else
            {
                this.UserId = UserId;
            }
            // to ensure "Scope" is required (not null)
            if (Scope == null)
            {
                throw new InvalidDataException("Scope is a required property for AddUserScopeRequest and cannot be null");
            }
            else
            {
                this.Scope = Scope;
            }
        }
        
        /// <summary>
        /// User to add the scope to
        /// </summary>
        /// <value>User to add the scope to</value>
        [DataMember(Name="userId", EmitDefaultValue=false)]
        public int? UserId { get; set; }

        /// <summary>
        /// Scope to add
        /// </summary>
        /// <value>Scope to add</value>
        [DataMember(Name="scope", EmitDefaultValue=false)]
        public string Scope { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AddUserScopeRequest {\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  Scope: ").Append(Scope).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AddUserScopeRequest);
        }

        /// <summary>
        /// Returns true if AddUserScopeRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of AddUserScopeRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AddUserScopeRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.UserId == input.UserId ||
                    (this.UserId != null &&
                    this.UserId.Equals(input.UserId))
                ) && 
                (
                    this.Scope == input.Scope ||
                    (this.Scope != null &&
                    this.Scope.Equals(input.Scope))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.UserId != null)
                    hashCode = hashCode * 59 + this.UserId.GetHashCode();
                if (this.Scope != null)
                    hashCode = hashCode * 59 + this.Scope.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
