/* 
 * Higgs API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// BotResponse
    /// </summary>
    [DataContract]
    public partial class BotResponse :  IEquatable<BotResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BotResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BotResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BotResponse" /> class.
        /// </summary>
        /// <param name="Id">Id (required).</param>
        /// <param name="Name">Name (required).</param>
        /// <param name="DashboardName">DashboardName (required).</param>
        /// <param name="Description">Description (required).</param>
        /// <param name="OwnerAccountId">OwnerAccountId.</param>
        /// <param name="Homepage">Homepage.</param>
        /// <param name="LogoUrl">LogoUrl.</param>
        /// <param name="FavIcon">FavIcon.</param>
        /// <param name="TabTitle">TabTitle.</param>
        public BotResponse(int? Id = default(int?), string Name = default(string), string DashboardName = default(string), string Description = default(string), int? OwnerAccountId = default(int?), string Homepage = default(string), string LogoUrl = default(string), string FavIcon = default(string), string TabTitle = default(string))
        {
            // to ensure "Id" is required (not null)
            if (Id == null)
            {
                throw new InvalidDataException("Id is a required property for BotResponse and cannot be null");
            }
            else
            {
                this.Id = Id;
            }
            // to ensure "Name" is required (not null)
            if (Name == null)
            {
                throw new InvalidDataException("Name is a required property for BotResponse and cannot be null");
            }
            else
            {
                this.Name = Name;
            }
            // to ensure "DashboardName" is required (not null)
            if (DashboardName == null)
            {
                throw new InvalidDataException("DashboardName is a required property for BotResponse and cannot be null");
            }
            else
            {
                this.DashboardName = DashboardName;
            }
            // to ensure "Description" is required (not null)
            if (Description == null)
            {
                throw new InvalidDataException("Description is a required property for BotResponse and cannot be null");
            }
            else
            {
                this.Description = Description;
            }
            this.OwnerAccountId = OwnerAccountId;
            this.Homepage = Homepage;
            this.LogoUrl = LogoUrl;
            this.FavIcon = FavIcon;
            this.TabTitle = TabTitle;
        }
        
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets DashboardName
        /// </summary>
        [DataMember(Name="dashboardName", EmitDefaultValue=false)]
        public string DashboardName { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets OwnerAccountId
        /// </summary>
        [DataMember(Name="ownerAccountId", EmitDefaultValue=false)]
        public int? OwnerAccountId { get; set; }

        /// <summary>
        /// Gets or Sets Homepage
        /// </summary>
        [DataMember(Name="homepage", EmitDefaultValue=false)]
        public string Homepage { get; set; }

        /// <summary>
        /// Gets or Sets LogoUrl
        /// </summary>
        [DataMember(Name="logoUrl", EmitDefaultValue=false)]
        public string LogoUrl { get; set; }

        /// <summary>
        /// Gets or Sets FavIcon
        /// </summary>
        [DataMember(Name="favIcon", EmitDefaultValue=false)]
        public string FavIcon { get; set; }

        /// <summary>
        /// Gets or Sets TabTitle
        /// </summary>
        [DataMember(Name="tabTitle", EmitDefaultValue=false)]
        public string TabTitle { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BotResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  DashboardName: ").Append(DashboardName).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  OwnerAccountId: ").Append(OwnerAccountId).Append("\n");
            sb.Append("  Homepage: ").Append(Homepage).Append("\n");
            sb.Append("  LogoUrl: ").Append(LogoUrl).Append("\n");
            sb.Append("  FavIcon: ").Append(FavIcon).Append("\n");
            sb.Append("  TabTitle: ").Append(TabTitle).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BotResponse);
        }

        /// <summary>
        /// Returns true if BotResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of BotResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BotResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.DashboardName == input.DashboardName ||
                    (this.DashboardName != null &&
                    this.DashboardName.Equals(input.DashboardName))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.OwnerAccountId == input.OwnerAccountId ||
                    (this.OwnerAccountId != null &&
                    this.OwnerAccountId.Equals(input.OwnerAccountId))
                ) && 
                (
                    this.Homepage == input.Homepage ||
                    (this.Homepage != null &&
                    this.Homepage.Equals(input.Homepage))
                ) && 
                (
                    this.LogoUrl == input.LogoUrl ||
                    (this.LogoUrl != null &&
                    this.LogoUrl.Equals(input.LogoUrl))
                ) && 
                (
                    this.FavIcon == input.FavIcon ||
                    (this.FavIcon != null &&
                    this.FavIcon.Equals(input.FavIcon))
                ) && 
                (
                    this.TabTitle == input.TabTitle ||
                    (this.TabTitle != null &&
                    this.TabTitle.Equals(input.TabTitle))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.DashboardName != null)
                    hashCode = hashCode * 59 + this.DashboardName.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.OwnerAccountId != null)
                    hashCode = hashCode * 59 + this.OwnerAccountId.GetHashCode();
                if (this.Homepage != null)
                    hashCode = hashCode * 59 + this.Homepage.GetHashCode();
                if (this.LogoUrl != null)
                    hashCode = hashCode * 59 + this.LogoUrl.GetHashCode();
                if (this.FavIcon != null)
                    hashCode = hashCode * 59 + this.FavIcon.GetHashCode();
                if (this.TabTitle != null)
                    hashCode = hashCode * 59 + this.TabTitle.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
