stages:
  - build
  - deploy

test server:
  stage: build
  image: microsoft/dotnet:latest
  script: 
    - cd Server
    - dotnet test Higgs.Server.Test

build server:
  stage: build
  image: microsoft/dotnet:latest
  script: 
    - cd Server
    - dotnet publish -c Release
  artifacts:
    paths:
      - Server/Higgs.Server/bin/Release/netcoreapp2.1/publish/*.*

build web:
  stage: build
  image: node:latest
  script: 
    - cd Web
    - npm install --unsafe-perm -g --silent @angular/cli
    - npm install --unsafe-perm --silent
    - ng build -prod
    - git rev-parse --verify HEAD > dist/assets/revision.txt
  artifacts:
    paths:
      - Web/dist

deploy production:
  environment: production
  stage: deploy
  image: node:latest
  only:
    - master
  variables:
    GIT_STRATEGY: none
    
  script:
    - apt-get -qq update
    - apt-get -qq -y install rsync
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo "$SSH_KEY_DEPLOY" > ~/.ssh/id_rsa
    - chown 400 ~/.ssh/id_rsa
    - ls -la
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - "ssh deploy@$PRODUCTION_IP 'mkdir -p /var/www/Higgs/Server'"
    - rsync -az --force --delete --progress -e "ssh -p22" Server/Higgs.Server/bin/Release/netcoreapp2.1/publish/* deploy@$PRODUCTION_IP:/var/www/Higgs/Server
    - "ssh deploy@$PRODUCTION_IP 'cp /var/www/Higgs/Configuration/appsettings.Production.json /var/www/Higgs/Server/.'"
    - "ssh deploy@$PRODUCTION_IP 'sudo systemctl restart higgs.server.service'"
    - rsync -az --force --delete --progress -e "ssh -p22" Web/dist/* deploy@$PRODUCTION_IP:/var/www/Higgs/Web/dist
    - rm ~/.ssh/id_rsa