/**
 * Higgs API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { ReportsByFeedbackResponse } from '../model/reportsByFeedbackResponse';
import { ReportsByReasonResponse } from '../model/reportsByReasonResponse';
import { ReportsOverTimeResponse } from '../model/reportsOverTimeResponse';
import { ReportsTotalResponse } from '../model/reportsTotalResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class AnalyticsService {

    protected basePath = 'https://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public analyticsReportsByFeedbackGet(observe?: 'body', reportProgress?: boolean): Observable<Array<ReportsByFeedbackResponse>>;
    public analyticsReportsByFeedbackGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ReportsByFeedbackResponse>>>;
    public analyticsReportsByFeedbackGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ReportsByFeedbackResponse>>>;
    public analyticsReportsByFeedbackGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<ReportsByFeedbackResponse>>(`${this.basePath}/Analytics/ReportsByFeedback`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public analyticsReportsByReasonGet(observe?: 'body', reportProgress?: boolean): Observable<Array<ReportsByReasonResponse>>;
    public analyticsReportsByReasonGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ReportsByReasonResponse>>>;
    public analyticsReportsByReasonGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ReportsByReasonResponse>>>;
    public analyticsReportsByReasonGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<ReportsByReasonResponse>>(`${this.basePath}/Analytics/ReportsByReason`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public analyticsReportsOverTimeGet(observe?: 'body', reportProgress?: boolean): Observable<Array<ReportsOverTimeResponse>>;
    public analyticsReportsOverTimeGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ReportsOverTimeResponse>>>;
    public analyticsReportsOverTimeGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ReportsOverTimeResponse>>>;
    public analyticsReportsOverTimeGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<ReportsOverTimeResponse>>(`${this.basePath}/Analytics/ReportsOverTime`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public analyticsReportsTotalGet(observe?: 'body', reportProgress?: boolean): Observable<Array<ReportsTotalResponse>>;
    public analyticsReportsTotalGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ReportsTotalResponse>>>;
    public analyticsReportsTotalGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ReportsTotalResponse>>>;
    public analyticsReportsTotalGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<ReportsTotalResponse>>(`${this.basePath}/Analytics/ReportsTotal`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
