/* 
 * Higgs API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ReviewerApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ReviewerApiTests
    {
        private ReviewerApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ReviewerApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReviewerApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ReviewerApi
            //Assert.IsInstanceOfType(typeof(ReviewerApi), instance, "instance is a ReviewerApi");
        }

        
        /// <summary>
        /// Test ReviewerAllReviewsGet
        /// </summary>
        [Test]
        public void ReviewerAllReviewsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ReviewerAllReviewsGet();
            
        }
        
        /// <summary>
        /// Test ReviewerFeedbackSendFeedbackPost
        /// </summary>
        [Test]
        public void ReviewerFeedbackSendFeedbackPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? reportId = null;
            //int? id = null;
            //instance.ReviewerFeedbackSendFeedbackPost(reportId, id);
            
        }
        
        /// <summary>
        /// Test ReviewerPendingReviewsGet
        /// </summary>
        [Test]
        public void ReviewerPendingReviewsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ReviewerPendingReviewsGet();
            
        }
        
        /// <summary>
        /// Test ReviewerReportGet
        /// </summary>
        [Test]
        public void ReviewerReportGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //var response = instance.ReviewerReportGet(id);
            //Assert.IsInstanceOf<ReviewerReportResponse> (response, "response is ReviewerReportResponse");
        }
        
        /// <summary>
        /// Test ReviewerReportsGet
        /// </summary>
        [Test]
        public void ReviewerReportsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ReviewerReportsGet();
            //Assert.IsInstanceOf<List<ReviewerReportsResponse>> (response, "response is List<ReviewerReportsResponse>");
        }
        
    }

}
