/**
 * Higgs API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BotResponseConflictExceptions } from './botResponseConflictExceptions';
import { BotResponseFeedback } from './botResponseFeedback';


export interface DashboardResponse {
    id: number;
    botName: string;
    dashboardName: string;
    description: string;
    requiredFeedback: number;
    requiredFeedbackConflicted: number;
    ownerAccountId?: number;
    homepage?: string;
    logoUrl?: string;
    favIcon?: string;
    tabTitle?: string;
    feedbacks?: Array<BotResponseFeedback>;
    conflictExceptions?: Array<BotResponseConflictExceptions>;
}
