/**
 * Higgs API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface EditCreateBotRequest {
    /**
     * Id of bot to be edited
     */
    botId: number;
    /**
     * Public key of bot used to sign JWT payloads
     */
    publicKey: string;
    /**
     * Name of the bot
     */
    name: string;
    /**
     * Description of the bot
     */
    description: string;
    homepage?: string;
    logoUrl?: string;
    favIcon?: string;
    tabTitle?: string;
}
