/**
 * Higgs API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface FeedbackType {
    /**
     * The name of the feedback type. Will be displayed on the dashboard. Must be unique per bot.
     */
    name: string;
    /**
     * The colour of the button reviewers will see when providing feedback
     */
    colour?: string;
    /**
     * A link to a feedback icon.
     */
    icon?: string;
    /**
     * Whether or not this feedback is actionable
     */
    isActionable?: boolean;
    /**
     * Number of required votes to mark the post as actioned
     */
    requiredActions?: number;
}
