/**
 * Higgs API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface RegisterPostReason {
    /**
     * The name of the reason
     */
    reasonName: string;
    /**
     * Confidence of the reason, between 0 and 1
     */
    confidence?: number;
}
