/**
 * Higgs API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ReviewerReportAllowedFeedbackResponse } from './reviewerReportAllowedFeedbackResponse';
import { ReviewerReportContentFragmentResponse } from './reviewerReportContentFragmentResponse';
import { ReviewerReportFeedbackResponse } from './reviewerReportFeedbackResponse';
import { ReviewerReportReasonResponse } from './reviewerReportReasonResponse';


export interface ReviewerReportResponse {
    id?: number;
    title?: string;
    botLogo?: string;
    botName?: string;
    dashboardName?: string;
    tabTitle?: string;
    favIcon?: string;
    botHomePage?: string;
    contentUrl?: string;
    contentSite?: string;
    contentType?: string;
    contentId?: number;
    detectionScore?: number;
    contentFragments?: Array<ReviewerReportContentFragmentResponse>;
    authorName?: string;
    authorReputation?: number;
    contentCreationDate?: Date;
    detectedDate?: Date;
    reasons?: Array<ReviewerReportReasonResponse>;
    allowedFeedback?: Array<ReviewerReportAllowedFeedbackResponse>;
    feedback?: Array<ReviewerReportFeedbackResponse>;
}
