/**
 * Higgs API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ReviewerReportFeedbackResponse } from './reviewerReportFeedbackResponse';


export interface ReviewerReportsResponse {
    id?: number;
    title?: string;
    dashboardName?: string;
    detectionScore?: number;
    feedback?: Array<ReviewerReportFeedbackResponse>;
}
