/* 
 * Higgs API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// RegisterUserFeedbackByContentRequest
    /// </summary>
    [DataContract]
    public partial class RegisterUserFeedbackByContentRequest :  IEquatable<RegisterUserFeedbackByContentRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RegisterUserFeedbackByContentRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RegisterUserFeedbackByContentRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RegisterUserFeedbackByContentRequest" /> class.
        /// </summary>
        /// <param name="ContentUrl">ContentUrl (required).</param>
        /// <param name="UserId">UserId (required).</param>
        /// <param name="Feedback">Feedback (required).</param>
        public RegisterUserFeedbackByContentRequest(string ContentUrl = default(string), int? UserId = default(int?), string Feedback = default(string))
        {
            // to ensure "ContentUrl" is required (not null)
            if (ContentUrl == null)
            {
                throw new InvalidDataException("ContentUrl is a required property for RegisterUserFeedbackByContentRequest and cannot be null");
            }
            else
            {
                this.ContentUrl = ContentUrl;
            }
            // to ensure "UserId" is required (not null)
            if (UserId == null)
            {
                throw new InvalidDataException("UserId is a required property for RegisterUserFeedbackByContentRequest and cannot be null");
            }
            else
            {
                this.UserId = UserId;
            }
            // to ensure "Feedback" is required (not null)
            if (Feedback == null)
            {
                throw new InvalidDataException("Feedback is a required property for RegisterUserFeedbackByContentRequest and cannot be null");
            }
            else
            {
                this.Feedback = Feedback;
            }
        }
        
        /// <summary>
        /// Gets or Sets ContentUrl
        /// </summary>
        [DataMember(Name="contentUrl", EmitDefaultValue=false)]
        public string ContentUrl { get; set; }

        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        [DataMember(Name="userId", EmitDefaultValue=false)]
        public int? UserId { get; set; }

        /// <summary>
        /// Gets or Sets Feedback
        /// </summary>
        [DataMember(Name="feedback", EmitDefaultValue=false)]
        public string Feedback { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RegisterUserFeedbackByContentRequest {\n");
            sb.Append("  ContentUrl: ").Append(ContentUrl).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  Feedback: ").Append(Feedback).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RegisterUserFeedbackByContentRequest);
        }

        /// <summary>
        /// Returns true if RegisterUserFeedbackByContentRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of RegisterUserFeedbackByContentRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RegisterUserFeedbackByContentRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ContentUrl == input.ContentUrl ||
                    (this.ContentUrl != null &&
                    this.ContentUrl.Equals(input.ContentUrl))
                ) && 
                (
                    this.UserId == input.UserId ||
                    (this.UserId != null &&
                    this.UserId.Equals(input.UserId))
                ) && 
                (
                    this.Feedback == input.Feedback ||
                    (this.Feedback != null &&
                    this.Feedback.Equals(input.Feedback))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ContentUrl != null)
                    hashCode = hashCode * 59 + this.ContentUrl.GetHashCode();
                if (this.UserId != null)
                    hashCode = hashCode * 59 + this.UserId.GetHashCode();
                if (this.Feedback != null)
                    hashCode = hashCode * 59 + this.Feedback.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
